### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by marusyaganza** [marusyaganza/lp-monorepo#58]
- [x] Evaluate word card design
- [x] Create a new Header design
- [x] Evaluate pages layout and create designs in Figma for main pages
- [x] Create games prototypes
- [x] Review and finish the designs for adding word functionality
- [x] Create a prototype and a visual design for a language selector
- [x] Create a visual design for the components that are required for games
- [x] Create a search field visual design
